######################## default configuration ####################
baseURL = "https://barrettventures.co.uk/"
title = "Sell Your Business - Barrett Ventures"
theme = "vex-hugo-master"

# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-168096882-1" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[permalinks]
blog = "/:title"
landingpages = "/:title"
mainpages = "/:title"

[params]
header = "Barrett Ventures"