# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Sell My Business"
url = "sell-my-business"
weight = 2

[[main]]
name = "About Us"
url = "about-us"
weight = 3

[[main]]
name = "Our Team"
url = "team"
weight = 4

[[main]]
name = "Contact"
url = "contact"
weight = 5

[[main]]
name = "Blog"
url = "blog"
weight = 6

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

[[footer_left]]
name = "Privacy Policy"
url = "privacy-notice"

[[footer_left]]
name = "Contact"
url = "contact"


# footer menu middle
[[footer_middle]]
name = "Pricing"
url = "pricing"

[[footer_middle]]
name = "Platform"
url = "#"

[[footer_middle]]
name = "Features"
url = "#"

# footer menu right
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"

[[footer_right]]
name = "FAQ"
url = "faq"