# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.
[params]
dateFormat = "2 January 2006"


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
primary_color = "#dfaa0a"
text_color = "#777"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#ECECEC"
black = "#000"
white = "#fff"
light = "#EDF6F5"

# font variable
# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400;500;600"
primary_font = "Lato:wght@400"
primary_font_type = "sans-serif" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"

# Regular CSS 
[[params.styles.css]]
link = "css/bootstrap.min.css"
[[params.styles.css]]
link = "css/animations.min.css"
[[params.styles.css]]
link = "css/default.css"
[[params.styles.css]]
link = "css/elementor-icons.min.css"
[[params.styles.css]]
link = "css/frontend.min.css"
[[params.styles.css]]
link = "css/frontend-legacy.min.css"
[[params.styles.css]]
link = "css/global.css"
[[params.styles.css]]
link = "css/post-13.css"
[[params.styles.css]]
link = "css/post-81.css"
[[params.styles.css]]
link = "css/post-218.css"
[[params.styles.css]]
link = "css/post-271.css"
[[params.styles.css]]
link = "css/style.min.css"
[[params.styles.css]]
link = "css/styles.css"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/brands.min.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/solid.min.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.slim.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
# [[params.plugins.js]]
# link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
# attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "skype"
icon = "fab fa-skype" # themify icon : https://themify.me/themify-icons
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"
